### ISSUE TITLE
✨ Notification - Add Blur to Overlay

### ISSUE THREAD

**Issue by alexlee-dev** [alexlee-dev/portfolio#486]
> Given that a notification displays, when the overlay is in view, then it also blurs the contents beneath it.

---

## Client
- [x] Adjust overlay style

```css
{
    backdrop-filter: blur(4px);
}
```
